=== nayanbhatia311/basic_web_prog/wdl/xml/details.dtd
<!ELEMENT STUDENTS (TITLE?,STUDENT*)>
<!ELEMENT TITLE(#PCDATA)>
<!ELEMENT STUDENT (NAME,ROLLNO,SUB*)>
<!ELEMENT NAME(#PCDATA)>
<!ELEMENT ROLLNO(#PCDATA)>
<!ELEMENT SUB(SUBNAME,MARKS)>
<!ELEMENT SUBNAME(#PCDATA)>
<!ELEMENT MARKS(#PCDATA)>

=== nayanbhatia311/basic_web_prog/wdl/xml/student.xml
<!DOCTYPE STUDENT SYSTEM "details.dtd">
<STUDENTS>
    <TITLE>RESULT OF COMPS</TITLE>
    <STUDENT>
        <NAME>KARTIK CHAWDA</NAME>
        <ROLLNO>59</ROLLNO>
        <SUB>
            <SUBNAME>WDL</SUBNAME>
            <MARKS>50</MARKS>
        </SUB>
        <SUB>
            <SUBNAME>DBMS</SUBNAME>
            <MARKS>70</MARKS>
        </SUB>
    </STUDENT>
    <STUDENT>
        <NAME>ABC</NAME>
        <ROLLNO>60</ROLLNO>
        <SUB>
            <SUBNAME>WDL</SUBNAME>
            <MARKS>39</MARKS>
        </SUB>
        <SUB>
            <SUBNAME>DBMS</SUBNAME>
            <MARKS>90</MARKS>
        </SUB>
    </STUDENT>
</STUDENTS>
